# Dockerfile

# 공식 엘라스틱서치 8.17.4 이미지를 기반으로 사용
FROM docker.elastic.co/elasticsearch/elasticsearch:8.17.4

# analysis-nori 플러그인 설치
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-nori